<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="Artists.xsl" type="text/xsl" ?>
<!DOCTYPE Artists
[
	<!ELEMENT Artists (Artist+)>
	<!ELEMENT Artist (name, desc, awards, popularAlbums, src)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT desc (#PCDATA)>
	<!ELEMENT awards (#PCDATA)>
	<!ELEMENT popularAlbums (#PCDATA)>	
	<!ELEMENT src (#PCDATA)>
]>
<!--CREDIT: Written by https://www.github.com/JaferDev-->
<!--XML Document for storing all information on artists
	STEPS TO ADD A NEW ARTIST:
		1. Download image of artist and add into folder
		2. Fulfill all requirements given in DTD (Line 3-12)
			2.1. <name>: Artist name
			2.2. <desc>: Short description of artist
			2.3. <awards>: Sentence listing few awards obtained by artist
			2.4. <popularAlbums>: Sentence listing few popular albums by artist
			2.5. <src>: Path to downloaded image of artist
-->

<Artists>
	<Artist>
		<name>Kendrick Lamar</name>
		<desc>American rapper, songwriter, and producer from Compton, California</desc>
		<awards>27 Grammys Awards, 2 Emmy Awards, and 5 American Music Awards</awards>
		<popularAlbums>good kid, m.A.A.d city, DAMN., and To Pimp A Butterfly</popularAlbums>
		<src>ArtistsImages/KendrickLamar.jpg</src>
	</Artist>
	
	<Artist>
		<name>Michael Jackson</name>
		<desc>American singer, songwriter, dancer, and philanthropist. One of the most culturally significant people in the 20th Century</desc>
		<awards>13 Number 1 Singles, 39 Guinness World Records, and 13 Grammy Awards</awards>
		<popularAlbums>Bad and Thriller</popularAlbums>
		<src>ArtistsImages/MichaelJackson.jpg</src>
	</Artist>	
	
	<Artist>
		<name>Bruno Mars</name>
		<desc>American singer-songwriter, producer, and dancer from Honolulu, Hawaii</desc>
		<awards>16 Grammry Awards and 10 Guinness World Rcoreds</awards>
		<popularAlbums>24K Magic and An Evening with Silk Sonic</popularAlbums>
		<src>ArtistsImages/BrunoMars.jpg</src>
	</Artist>
	
	<Artist>
		<name>Dua Lipa</name>
		<desc>English singer and songwriter</desc>
		<awards>3 Grammy Awards and 7 Brit Awards</awards>
		<popularAlbums>Future Nostalgia</popularAlbums>
		<src>ArtistsImages/DuaLipa.jpeg</src>
	</Artist>

	<Artist>
		<name>Rema</name>
		<desc>Nigerian singer-songwriter and rapper</desc>
		<awards>6 AFRIMMA Awards and 6 The Headies Awards</awards>
		<popularAlbums>Raves and Roses</popularAlbums>
		<src>ArtistsImages/Rema.jpg</src>
	</Artist>

	<Artist>
		<name>Selena Gomez</name>
		<desc>American actress, singer-songwriter, businesswoman, and producer</desc>
		<awards>1 American Music Award and 1 Billboard Music Award</awards>
		<popularAlbums>Revival</popularAlbums>
		<src>ArtistsImages/SelenaGomez.webp</src>
	</Artist>

	<Artist>
		<name>Fireboy DML</name>
		<desc>Nigerian singer-songwriter</desc>
		<awards>6 The Headies Awards</awards>
		<popularAlbums>Playboy</popularAlbums>
		<src>ArtistsImages/FireboyDML.jpeg</src>
	</Artist>

	<Artist>
		<name>Ed Sheeran</name>
		<desc>English singer-songwriter and musician</desc>
		<awards>4 Grammy Awards</awards>
		<popularAlbums>÷ and x</popularAlbums>
		<src>ArtistsImages/EdSheeran.webp</src>
	</Artist>

	<Artist>
		<name>Victony</name>
		<desc>Nigerian singer-songwriter and rapper</desc>
		<awards>1 The Headies Awards</awards>
		<popularAlbums>Stubborn</popularAlbums>
		<src>ArtistsImages/Victony.jpg</src>
	</Artist>

	<Artist>
		<name>The Weeknd</name>
		<desc>Canadian singer-songwriter and record producer</desc>
		<awards>4 Grammy Awards</awards>
		<popularAlbums>After Hours and Starboy</popularAlbums>
		<src>ArtistsImages/TheWeeknd.jpg</src>
	</Artist>

	<Artist>
		<name>Travis Scott</name>
		<desc>American rapper, singer-songwriter, and producer</desc>
		<awards>10 Grammy Award Nominations</awards>
		<popularAlbums>Astroworld and Rodeo</popularAlbums>
		<src>ArtistsImages/TravisScott.webp</src>
	</Artist>
	
	<Artist>
		<name>Tyla</name>
		<desc>South-African singer-songwriter</desc>
		<awards>1 Grammy Award</awards>
		<popularAlbums>Tyla</popularAlbums>
		<src>ArtistsImages/Tyla.jpeg</src>
	</Artist>

</Artists>